-- 문제 출처: 프로그래머스 코딩 테스트 연습, https://programmers.co.kr/learn/challenges
WITH HOUR_TMP AS
(
    SELECT
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
    FROM ANIMAL_OUTS
)

SELECT 
    A.HOUR_BASE AS HOUR
    ,CASE WHEN B.CNT IS NULL THEN 0 ELSE B.CNT END AS COUNT
FROM (SELECT LEVEL-1 AS HOUR_BASE FROM DUAL CONNECT BY LEVEL <= 24) A
LEFT JOIN (SELECT HOUR, COUNT(*) AS CNT FROM HOUR_TMP GROUP BY HOUR) B ON A.HOUR_BASE = B.HOUR
ORDER BY A.HOUR_BASE ASC
;
